
#include "integrator/pathTracerGuided.hpp"
#include "bsdf/bsdfSample.hpp"
#include "core/instance.hpp"
#include "core/random.hpp"
#include "core/ray.hpp"
#include "core/scene.hpp"
#include "intersection/intersection.hpp"
#include "math/mathUtil.hpp"
#include "bsdf/bsdf.hpp"
#include "pathGuiding/kdTree.hpp"
#include "pathGuiding/quadTree.hpp"
#include "math/constants.hpp"


namespace pathtracer{

    std::atomic<long long> PathTracerGuided::n1{0};
    std::atomic<long long> PathTracerGuided::n2{0};
    

    PathTracerGuided::PathTracerGuided(int maxDepth, real alpha) :
        m_maxDepth{maxDepth}, m_alpha{alpha} {}


    Vector3 PathTracerGuided::color(
        const Ray& ray, const Scene& scene) {

        Ray currRay = ray;
        Vector3 color = Vector3(0.0);
        Vector3 throughput = Vector3(1.0);

        // Used for path guiding training
        std::vector<Vector3> positions;
        std::vector<Vector3> weights;
        std::vector<Vector3> directions;

        for(int i = 0; i < m_maxDepth; i++){

            Vector3 wo = -currRay.direction();

            // First we intersect the scene
            Intersection it = scene.intersect(currRay);
            // If no hits (we can break or sample envmap)
            if(!it){
                recordPath(positions, directions, weights, Vector3(0.0), scene);
                break;
            }

            // If we have an emissive surface, add emission and break
            if(it.instance()->emission()){
                Vector3 emission = it.evaluateEmission(wo);
                color = color + emission * throughput;

                // Saved for training
                recordPath(positions, directions, weights, emission, scene);
                break;
            }

            // ------ This next step is normal pathtracer ------

            // Russian roulette
            real p = Util::russianRoulette(throughput);
            if (Random::next() > p){
                recordPath(positions, directions, weights, Vector3(0.0), scene);
                break;
            }

            // If we have a non-null guide tree, we can use it to guide
            // samples.

            // ---------------------- PATH GUIDING ------------------------

            Vector3 wi;
            Vector3 weight;
            real pdf;
            BsdfSample sample;

            if(m_guideTree && !it.instance()->bsdf()->isSpecular()){

                Vector3 localPoint =
                    toTreeLocalSpace(it.position(), scene);

                auto dTree = m_guideTree->getDTree(localPoint);

                // We use MIS to blend the two guiding techniques
                if(Random::next() < m_alpha){
                    wi = dTree->sample();
                    sample = it.evaluateBsdf(wo, wi);
                }
                else{
                    sample = it.sampleBsdf(wo);
                    wi = sample.wi();
                }

                if(sample.isInvalid()){
                    weights.push_back(Vector3(0.0));
                    positions.push_back(it.position());
                    directions.push_back(wi);
                    recordPath(positions, directions, weights, Vector3(0.0), scene);
                    break;
                }

                // Whether wi we generated by either method, these
                // values record the pdf that the either method generated
                // wi. We can assume the pdf is always valid since
                // we only do this for non-specular surfaces with valid pdf.
                real guidePdf = dTree->pdf(wi);
                real bsdfPdf = sample.pdf();

                pdf = m_alpha * guidePdf + (1 - m_alpha) * bsdfPdf;
                weight = sample.bsdf() * sample.cosine() / pdf;
            }

            // If the previous sample was ivalid or specular or if there is no guide tree,
            // we use bsdf sample.
            else{
                sample = it.sampleBsdf(wo);
                wi = sample.wi();
                weight = sample.weight();
                pdf = sample.pdf();

                // It is invalid we can't go further
                if(sample.isInvalid()){
                    break;
                }
            }

            // And we update the throughput (along with RR probability)
            weight = weight * (1.0f / p);

            // We then store, in a stack, the position, and the throughput
            // at this point.
            if(m_trainTree){
                weights.push_back(weight);
                positions.push_back(it.position());
                directions.push_back(wi);
            }

            throughput = throughput * weight;
            // The new ray starts at the last intersected point
            // and points towards the new intersected point.
            currRay = Ray(it.position() + wi * SHADOW_EPSILON, wi);
        }

        return color;
    }

}