 
#ifndef PATH_TRACER_PATH_TRACER_GUIDED_HPP
#define PATH_TRACER_PATH_TRACER_GUIDED_HPP

#include "integrator.hpp"
#include "guidable.hpp"

namespace pathtracer{

    // A pure path tracer
    class PathTracerGuided: public Integrator, public Guidable {

    private:

        int m_maxDepth;

        // Weight used when combining bsdf sampling with guiding
        // (defensive sampling).
        real m_alpha;
        
    public:

        PathTracerGuided(int maxDepth, real alpha) : m_maxDepth{maxDepth},
            m_alpha{alpha}{}

        Vector3 color(const Ray& ray, const Scene& scene) const override{

            Ray currRay = ray;
            Vector3 color = Vector3(0.0);
            Vector3 throughput = Vector3(1.0);

            
            // Used for path guiding training
            std::stack<Vector3> positionStack;
            std::stack<Vector3> weightStack;
            std::stack<Vector3> directionStack;
            Vector3 emissionValue(0.0);
            bool completePath = false;


            for(int i = 0; i < m_maxDepth; i++){

                Vector3 wo = -currRay.direction();

                // First we intersect the scene
                Intersection it = scene.intersect(currRay);
                // If no hits (we can break or sample envmap)
                if(!it){
                    break;
                }

                // If we have an emissive surface, add emission and break
                if(it.instance()->emission()){
                    Vector3 emission = it.evaluateEmission(wo);
                    color = color + emission * throughput;

                    // Saved for training
                    emissionValue = emission;
                    completePath = true;

                    break;
                }

                // ------ This next step is normal pathtracer ------

                // Russian roulette
                // No RR when not training (final render)
                real p = 1.0;
                if(m_trainTree){
                    p = Util::russianRoulette(throughput);
                    if (Random::next() > p){
                        break;
                    }
                }


                // If we have a non-null guide tree, we can use it to guide
                // samples.

                // ---------------------- PATH GUIDING ------------------------

                Vector3 wi;
                Vector3 localWi;
                Vector3 weight;
                real pdf;               
                BsdfSample sample;

                if(m_guideTree && !it.instance()->bsdf()->isSpecular()){
                
                    Vector3 localPoint = toTreeLocalSpace(it.position(), scene);
                    auto dTree = m_guideTree->getDTree(localPoint);

                    // We use MIS to blend the two guiding techniques
                    if(Random::next() < m_alpha){
                        // Wi is in local coordinates
                        localWi = dTree->sample();
                        wi = it.shadingFrame().inverseTransformDirection(localWi);
                        sample = it.evaluateBsdf(wo, wi);
                    }
                    else{
                        sample = it.sampleBsdf(wo);
                        wi = sample.wi();
                        localWi = it.shadingFrame().transformDirection(wi);
                    }
                    
                    // Whether wi we generated by either method, these
                    // values record the pdf that the either method generated
                    // wi. We can assume the pdf is always valid since
                    // we only do this for non-specular surfaces with valid pdf.
                    real guidePdf = dTree->pdf(localWi);
                    real bsdfPdf = sample.pdf();
                    
                    pdf = m_alpha * guidePdf + (1 - m_alpha) * bsdfPdf;
                    weight = sample.bsdf() * sample.cosine() / pdf;
                }

                // If the previous sample was ivalid or specular or if there is no guide tree,
                // we use bsdf sample.
                if(!m_guideTree || it.instance()->bsdf()->isSpecular() || sample.isInvalid()){

                    sample = it.sampleBsdf(wo);
                    wi = sample.wi();
                    weight = sample.weight();
                    localWi = it.shadingFrame().transformDirection(wi);
                    pdf = sample.pdf();
                }

                // We then store, in a stack, the position, and the throughput 
                // at this point.
                if(m_trainTree){
                    weightStack.push(weight);
                    positionStack.push(it.position());
                    directionStack.push(localWi);
                }

                // And we update the throughput (along with RR probability)
                weight = weight * (1.0f / p);
                throughput = throughput * weight;
                // The new ray starts at the last intersected point
                // and points towards the new intersected point.
                currRay = Ray(it.position() + wi * SHADOW_EPSILON, wi);   
                
            }

            // Now, at the end, we train the training tree, if there is one
            if(m_trainTree){

                Vector3 intensity = emissionValue;

                while(!positionStack.empty()){

                    Vector3 localPoint = toTreeLocalSpace(positionStack.top(), scene);
                    Vector3 direction = directionStack.top();

                    intensity = intensity * weightStack.top(); 

                    if(isfinite(intensity.x())&&
                        isfinite(intensity.y()) &&
                        isfinite(intensity.z())){
                        m_trainTree->accumulate(
                            localPoint,
                            direction,
                            intensity.luminance()
                        );
                    }
                    else{
                        // Weight is corrupted from somewhere
                        break;
                    }

                    // We then pop the stack etc...
                    weightStack.pop();
                    positionStack.pop();
                    directionStack.pop();
                }

            }
            
                
            return color;
        }

    };

}

#endif